eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

okta:
  oauth2:
    issuer: https://dev-31074102.okta.com/oauth2/default
    audience: api://default
